name: Prebuild Codespaces

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Weekly prebuild refresh

jobs:
  prebuild:
    name: Create Codespaces Prebuild
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Codespaces environment
        uses: github/codespaces-precache@v1
        with:
          cache-steps: |
            - name: Install dependencies
              run: pip install -r requirements.txt && reflex init